apiVersion: v1
kind: Service
metadata:
  name: {{ include "zveltio.fullname" . }}-engine
  labels:
    {{- include "zveltio.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
  {{- with .Values.engine.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zveltio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: engine
