/**
 * Schema Watcher (P6 — End-to-End Type Safety)
 *
 * Watches the Zveltio engine for DDL schema changes via WebSocket and
 * regenerates a TypeScript types file whenever a collection is created,
 * updated, or deleted.
 *
 * Usage (in `zveltio dev --watch`):
 *   import { watchSchema } from '@zveltio/sdk/schema-watcher';
 *   await watchSchema('http://localhost:3000', './src/zveltio-types.d.ts');
 */

export interface CollectionField {
  name: string;
  type: string;
  required?: boolean;
}

export interface CollectionSchema {
  name: string;
  display_name?: string;
  fields: CollectionField[];
}

export interface WatchSchemaOptions {
  /** API token for the engine (admin key) */
  apiKey?: string;
  /** Reconnect delay in ms (default: 3000) */
  reconnectDelay?: number;
  /** Called after each successful type regeneration */
  onUpdate?: (collections: CollectionSchema[]) => void;
  /** Called on connection errors */
  onError?: (err: Error) => void;
}

const TYPE_MAP: Record<string, string> = {
  text: 'string',
  textarea: 'string',
  richtext: 'string',
  email: 'string',
  url: 'string',
  slug: 'string',
  color: 'string',
  phone: 'string',
  password: 'string',
  uuid: 'string',
  enum: 'string',
  tags: 'string[]',
  integer: 'number',
  float: 'number',
  number: 'number',
  boolean: 'boolean',
  date: 'string',
  datetime: 'string',
  json: 'Record<string, unknown>',
  file: 'string',
  image: 'string',
  location: '{ lat: number; lng: number }',
  geometry: 'GeoJSON.Geometry',
  vector: 'number[]',
  m2o: 'string',
  o2m: 'string[]',
  m2m: 'string[]',
};

function fieldToType(field: CollectionField): string {
  return TYPE_MAP[field.type] ?? 'unknown';
}

function collectionToInterface(col: CollectionSchema): string {
  const lines = [`export interface ${toPascalCase(col.name)} {`];
  lines.push(`  id: string;`);
  lines.push(`  created_at: string;`);
  lines.push(`  updated_at: string;`);

  for (const field of col.fields) {
    const tsType = fieldToType(field);
    const optional = field.required ? '' : '?';
    lines.push(`  ${field.name}${optional}: ${tsType};`);
  }

  lines.push(`}`);
  return lines.join('\n');
}

function generateTypesFile(collections: CollectionSchema[]): string {
  const header = `// Auto-generated by @zveltio/sdk schema-watcher
// Do not edit manually — changes will be overwritten on schema updates.
// Generated at: ${new Date().toISOString()}

`;

  const interfaces = collections.map(collectionToInterface).join('\n\n');

  const collectionNames = collections.map((c) => `'${c.name}'`).join(' | ');
  const collectionMap = collections
    .map((c) => `  ${c.name}: ${toPascalCase(c.name)};`)
    .join('\n');

  const clientType = `
export type CollectionName = ${collectionNames || 'never'};

export interface CollectionTypeMap {
${collectionMap}
}

/** Pass this to createZveltioClient<ZveltioSchema>() for full type inference */
export type ZveltioSchema = CollectionTypeMap;
`;

  return header + interfaces + clientType;
}

function toPascalCase(str: string): string {
  return str
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

async function fetchCollections(engineUrl: string, apiKey?: string): Promise<CollectionSchema[]> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (apiKey) headers['Authorization'] = `Bearer ${apiKey}`;

  const res = await fetch(`${engineUrl}/api/collections`, { headers });
  if (!res.ok) throw new Error(`Failed to fetch collections: ${res.status}`);

  const data = await res.json();
  return data.collections || [];
}

async function writeTypes(outputPath: string, content: string): Promise<void> {
  // Use Bun.file in Bun runtime, fall back to dynamic import of fs in Node
  if (typeof Bun !== 'undefined') {
    await Bun.write(outputPath, content);
  } else {
    const { writeFile } = await import('node:fs/promises');
    await writeFile(outputPath, content, 'utf8');
  }
}

/**
 * Start watching the engine's WebSocket for schema changes and regenerate
 * TypeScript types at `outputPath` whenever the schema changes.
 *
 * Returns a cleanup function that closes the WebSocket.
 */
export async function watchSchema(
  engineUrl: string,
  outputPath: string,
  options: WatchSchemaOptions = {},
): Promise<() => void> {
  const { apiKey, reconnectDelay = 3000, onUpdate, onError } = options;

  // Generate initial types on startup
  try {
    const collections = await fetchCollections(engineUrl, apiKey);
    const content = generateTypesFile(collections);
    await writeTypes(outputPath, content);
    console.log(`[zveltio] ✓ Types generated at ${outputPath} (${collections.length} collections)`);
    onUpdate?.(collections);
  } catch (err) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.warn(`[zveltio] Could not generate initial types:`, e.message);
    onError?.(e);
  }

  const wsUrl = engineUrl.replace(/^http/, 'ws') + '/api/ws';
  let ws: WebSocket | null = null;
  let stopped = false;

  function connect() {
    if (stopped) return;

    ws = new WebSocket(wsUrl);

    ws.onopen = () => {
      console.log('[zveltio] Schema watcher connected.');
      // Subscribe to all schema change events
      ws!.send(JSON.stringify({ type: 'subscribe', channel: 'schema' }));
    };

    ws.onmessage = async (event) => {
      try {
        const msg = JSON.parse(event.data);
        const isSchemaChange =
          msg.event === 'schema:changed' ||
          msg.type === 'schema:changed' ||
          ['create_collection', 'drop_collection', 'add_field', 'drop_field'].includes(msg.event);

        if (!isSchemaChange) return;

        const collections = await fetchCollections(engineUrl, apiKey);
        const content = generateTypesFile(collections);
        await writeTypes(outputPath, content);

        const changed = msg.collection ?? msg.data?.collection ?? '?';
        console.log(`[zveltio] ✓ Types updated — ${changed} changed (${collections.length} total)`);
        onUpdate?.(collections);
      } catch (err) {
        // Non-fatal: keep watching
      }
    };

    ws.onclose = () => {
      if (!stopped) {
        console.log(`[zveltio] Schema watcher disconnected. Reconnecting in ${reconnectDelay}ms…`);
        setTimeout(connect, reconnectDelay);
      }
    };

    ws.onerror = (event) => {
      const err = new Error('WebSocket error');
      onError?.(err);
    };
  }

  connect();

  return () => {
    stopped = true;
    ws?.close();
    console.log('[zveltio] Schema watcher stopped.');
  };
}

/** One-shot type generation without watching. */
export async function generateTypes(
  engineUrl: string,
  outputPath: string,
  apiKey?: string,
): Promise<void> {
  const collections = await fetchCollections(engineUrl, apiKey);
  const content = generateTypesFile(collections);
  await writeTypes(outputPath, content);
  console.log(`[zveltio] ✓ Types generated at ${outputPath} (${collections.length} collections)`);
}
