-- A user id does not fit in a uuid column.
--
-- `"user".id` is a 32-character nanoid and always was; these columns were
-- declared UUID because a name like `created_by` reads as a foreign key to a
-- table whose primary key happens to be one. Postgres rejects the write with
-- 22P02 `invalid input syntax for type uuid`, so the routes that write them
-- returned 500 to every caller — not intermittent, not a permission problem, the
-- feature simply never worked.
--
-- This is the host's share of a sweep that also touched seven extensions, and it
-- is deliberately one table.
--
-- `zv_pages.updated_by` looked like it belonged here too: the engine creates
-- `zv_pages` in 001_initial.sql and reads it for the sitemap. It does not. The
-- COLUMN is added by content/page-builder's own 001_initial.sql
-- (`ALTER TABLE zv_pages ADD COLUMN IF NOT EXISTS updated_by UUID`), so on a
-- database with no extensions it does not exist and this migration died on it —
-- `column "updated_by" of relation "zv_pages" does not exist`, engine refusing
-- to boot.
--
-- Ownership is per column, not per table: the host owns `zv_pages`, the
-- extension owns what it adds to it, and each repairs its own.
--
-- Found by pressing the button on a virgin database, which is the only place
-- this is visible: on an instance that has been in use, some of these columns
-- were altered by hand at some point. That is also why the earlier repair in
-- compliance/ro/documents (`003_user_ref_text.sql`) fixed exactly one column and
-- left its own siblings — somebody mended the instance in front of them rather
-- than the class.
--
-- Only columns that actually RECEIVE `user.id` are converted, established by
-- reading each INSERT/UPDATE against its bound values. `zv_rate_limit_configs.updated_by`
-- is deliberately left alone: it is a uuid with a matching name that NOTHING
-- writes, which is a different defect and not this one.
--
-- uuid → text needs no USING clause and preserves existing values.

ALTER TABLE IF EXISTS zv_edge_functions ALTER COLUMN created_by TYPE TEXT;
