/**
 * The installed schema as sorted, diffable text: columns, keys, unique
 * indexes, RLS and policies of every `public` table. `scripts/schema-snapshot.ts`
 * records it for a full install; the schema-as-code acceptance test compares
 * it before and after an apply (RFC schema-as-code §9).
 */
import type { SQL } from 'bun';

interface Row {
  [k: string]: unknown;
}

/** Render the whole schema as sorted, diffable text. */
export async function renderInstalledSchema(db: SQL): Promise<string> {
  const cols = (await db`
    SELECT table_name AS t, column_name AS c, data_type AS ty,
           is_nullable AS nul, column_default AS def
      FROM information_schema.columns
     WHERE table_schema = 'public'
     ORDER BY table_name, column_name
  `) as Row[];

  const cons = (await db`
    SELECT c.relname AS t, con.conname AS name, con.contype::text AS kind,
           pg_get_constraintdef(con.oid) AS def
      FROM pg_constraint con
      JOIN pg_class c ON c.oid = con.conrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND con.contype IN ('p','u','f','c')
     ORDER BY c.relname, con.conname
  `) as Row[];

  // Unique indexes that are not already a constraint. `CREATE UNIQUE INDEX`
  // never appears in pg_constraint, and it is where several of this schema's
  // real keys live.
  const idx = (await db`
    SELECT i.tablename AS t, i.indexname AS name, i.indexdef AS def
      FROM pg_indexes i
     WHERE i.schemaname = 'public'
       AND i.indexdef ILIKE '%UNIQUE INDEX%'
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conname = i.indexname)
     ORDER BY i.tablename, i.indexname
  `) as Row[];

  const rls = (await db`
    SELECT c.relname AS t, c.relrowsecurity AS on, c.relforcerowsecurity AS forced
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
     ORDER BY c.relname
  `) as Row[];

  const pol = (await db`
    SELECT c.relname AS t, p.polname AS name, p.polcmd::text AS cmd,
           COALESCE(pg_get_expr(p.polqual, p.polrelid), '-') AS using_expr,
           COALESCE(pg_get_expr(p.polwithcheck, p.polrelid), '-') AS check_expr
      FROM pg_policy p
      JOIN pg_class c ON c.oid = p.polrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public'
     ORDER BY c.relname, p.polname
  `) as Row[];

  const by = <T extends Row>(rows: T[]): Map<string, T[]> => {
    const m = new Map<string, T[]>();
    for (const r of rows) {
      const k = String(r.t);
      (m.get(k) ?? m.set(k, []).get(k)!).push(r);
    }
    return m;
  };
  const colsBy = by(cols);
  const consBy = by(cons);
  const idxBy = by(idx);
  const polBy = by(pol);
  const rlsBy = new Map(rls.map((r) => [String(r.t), r]));

  const KIND: Record<string, string> = { p: 'pk', u: 'uq', f: 'fk', c: 'ck' };
  const tables = [...colsBy.keys()].sort();
  const out: string[] = [
    '# Zveltio — schema of a full install (engine + every extension).',
    '#',
    '# Generated by `bun run scripts/schema-snapshot.ts --write`. Do not hand-edit.',
    '# A diff here is a real change to what a customer gets; read it before',
    '# committing it. See the header of that script for why this file exists.',
    '#',
    `# tables: ${tables.length}`,
    '',
  ];

  for (const t of tables) {
    out.push(`table ${t}`);
    for (const c of colsBy.get(t) ?? []) {
      const parts = [`  col ${String(c.c).padEnd(30)} ${String(c.ty)}`];
      if (c.nul === 'NO') parts.push('NOT NULL');
      if (c.def != null) parts.push(`DEFAULT ${String(c.def)}`);
      out.push(parts.join(' '));
    }
    for (const k of consBy.get(t) ?? []) {
      out.push(`  ${KIND[String(k.kind)]}  ${String(k.name)} ${String(k.def)}`);
    }
    for (const i of idxBy.get(t) ?? []) {
      // Only the interesting half of indexdef — the ON clause onwards.
      const def = String(i.def).replace(/^CREATE UNIQUE INDEX \S+ ON \S+ USING \S+ /, '');
      out.push(`  idx ${String(i.name)} UNIQUE ${def}`);
    }
    const r = rlsBy.get(t);
    if (r) out.push(`  rls enabled${r.forced ? ' forced' : ''}`);
    for (const p of polBy.get(t) ?? []) {
      out.push(
        `  pol ${String(p.name)} FOR ${String(p.cmd)} USING ${String(p.using_expr)} CHECK ${String(p.check_expr)}`,
      );
    }
    out.push('');
  }
  return out.join('\n');
}
