// AUTO-GENERATED by scripts/sync-extensions.ts — do not edit.
// Re-run `bun scripts/sync-extensions.ts` after adding or removing studio/src/contribute.ts.

export const CONTRIBUTION_MODULES: Record<
  string,
  () => Promise<{ activate?: () => void }>
> = {
  "crm": () => import("./crm/contribute.js"),
};
