// Run before bun build --compile
// Transforms all files from studio-dist/ into a TypeScript object embedded in the binary
// Uses Bun-native APIs (Bun.file, Bun.Glob, Bun.write, Bun.exit)

/// <reference types="bun-types" />

import { join } from 'path';

const STUDIO_DIST = join(import.meta.dir, '../src/studio-dist');
const OUTPUT_FILE = join(import.meta.dir, '../src/studio-embed/index.ts');

const BINARY_EXTENSIONS = new Set([
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.ico',
  '.webp',
]);

async function generateEmbed() {
  // Check if studio-dist exists using Bun.file()
  const studioDir = Bun.file(STUDIO_DIST);
  if (!(await studioDir.exists())) {
    console.error(
      '❌ studio-dist/ not found. Run: cd ../studio && bun run build first.',
    );
    process.exit(1);
  }

  const files: Record<string, string> = {};

  // Use Bun.Glob to walk the directory
  const glob = new Bun.Glob('**/*');

  for await (const file of glob.scan({ cwd: STUDIO_DIST })) {
    const fullPath = join(STUDIO_DIST, file);
    const bunFile = Bun.file(fullPath);

    // Skip directories
    const stat = await bunFile.stat();
    if (!stat || stat.isDirectory()) continue;

    const key = '/' + file.replace(/\\/g, '/');
    const ext = file.substring(file.lastIndexOf('.')).toLowerCase();
    const isBinary = BINARY_EXTENSIONS.has(ext);

    if (isBinary) {
      // Read as ArrayBuffer and convert to base64
      const buffer = await bunFile.arrayBuffer();
      files[key] = Buffer.from(buffer).toString('base64');
    } else {
      // Read as text
      files[key] = await bunFile.text();
    }
  }

  const fileCount = Object.keys(files).length;

  const output = `// AUTO-GENERATED — do not edit manually
// Generated by scripts/generate-studio-embed.ts
// ${fileCount} files embedded

const BINARY_EXTENSIONS = new Set(['.woff', '.woff2', '.ttf', '.eot', '.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp']);

const studioFiles: Record<string, string> = ${JSON.stringify(files, null, 2)};

export function getStudioFile(path: string): { content: string | Uint8Array; isBinary: boolean } | null {
  const file = studioFiles[path];
  if (!file) return null;

  const ext = path.includes('.') ? path.substring(path.lastIndexOf('.')).toLowerCase() : '';
  const isBinary = BINARY_EXTENSIONS.has(ext);

  if (isBinary) {
    const bytes = Buffer.from(file, 'base64');
    return { content: new Uint8Array(bytes), isBinary: true };
  }

  return { content: file, isBinary: false };
}

export function studioFileExists(path: string): boolean {
  return path in studioFiles;
}
`;

  // Use Bun.write to create the output file
  await Bun.write(OUTPUT_FILE, output);
  console.log(`✅ Studio embed generated: ${fileCount} files → ${OUTPUT_FILE}`);
}

await generateEmbed();
