// Run before bun build --compile
// Transforms all files from studio-dist/ into a TypeScript object embedded in the binary
// Uses Bun-native APIs (Bun.file, Bun.Glob, Bun.write, Bun.exit)
//
// Always writes packages/engine/src/studio-embed/index.ts:
//   - full embed when src/studio-dist/ exists
//   - empty stub otherwise (so imports resolve for typecheck / compile)
//
// Do NOT commit a full embed — check:studio-embed rejects index.ts > 50KB.

/// <reference types="bun-types" />

import { join } from 'path';

const STUDIO_DIST = join(import.meta.dir, '../src/studio-dist');
const OUTPUT_FILE = join(import.meta.dir, '../src/studio-embed/index.ts');

const BINARY_EXTENSIONS = new Set([
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.ico',
  '.webp',
]);

function stubSource(): string {
  return `// AUTO-GENERATED stub — scripts/generate-studio-embed.ts overwrites this when
// \`src/studio-dist/\` exists (binary builds). The committed copy is always empty
// so the module resolves for typecheck and \`bun --compile\` without embedding
// the Studio UI into git. Do not commit a regenerated full embed (CI rejects
// files over ~50KB via check:studio-embed).

const BINARY_EXTENSIONS = new Set([
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.ico',
  '.webp',
]);

const studioFiles: Record<string, string> = {};

export function getStudioFile(
  path: string,
): { content: string | Uint8Array; isBinary: boolean } | null {
  const file = studioFiles[path];
  if (!file) return null;

  const ext = path.includes('.') ? path.substring(path.lastIndexOf('.')).toLowerCase() : '';
  const isBinary = BINARY_EXTENSIONS.has(ext);

  if (isBinary) {
    const bytes = Buffer.from(file, 'base64');
    return { content: new Uint8Array(bytes), isBinary: true };
  }

  return { content: file, isBinary: false };
}

export function studioFileExists(path: string): boolean {
  return path in studioFiles;
}

/** True when generate-studio-embed inlined a real Studio build. */
export function studioEmbedActive(): boolean {
  return Object.keys(studioFiles).length > 0;
}
`;
}

function fullSource(files: Record<string, string>): string {
  const fileCount = Object.keys(files).length;
  return `// AUTO-GENERATED — do not edit manually
// Generated by scripts/generate-studio-embed.ts
// ${fileCount} files embedded
// WARNING: do not commit this file when it contains a full Studio build.

const BINARY_EXTENSIONS = new Set(['.woff', '.woff2', '.ttf', '.eot', '.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp']);

const studioFiles: Record<string, string> = ${JSON.stringify(files, null, 2)};

export function getStudioFile(path: string): { content: string | Uint8Array; isBinary: boolean } | null {
  const file = studioFiles[path];
  if (!file) return null;

  const ext = path.includes('.') ? path.substring(path.lastIndexOf('.')).toLowerCase() : '';
  const isBinary = BINARY_EXTENSIONS.has(ext);

  if (isBinary) {
    const bytes = Buffer.from(file, 'base64');
    return { content: new Uint8Array(bytes), isBinary: true };
  }

  return { content: file, isBinary: false };
}

export function studioFileExists(path: string): boolean {
  return path in studioFiles;
}

export function studioEmbedActive(): boolean {
  return Object.keys(studioFiles).length > 0;
}
`;
}

async function generateEmbed() {
  const index = Bun.file(join(STUDIO_DIST, 'index.html'));
  if (!(await index.exists())) {
    await Bun.write(OUTPUT_FILE, stubSource());
    console.log(`⚠️  studio-dist/ missing — wrote empty studio-embed stub → ${OUTPUT_FILE}`);
    return;
  }

  const files: Record<string, string> = {};
  const glob = new Bun.Glob('**/*');

  for await (const file of glob.scan({ cwd: STUDIO_DIST })) {
    const fullPath = join(STUDIO_DIST, file);
    const bunFile = Bun.file(fullPath);
    const stat = await bunFile.stat();
    if (!stat || stat.isDirectory()) continue;

    const key = '/' + file.replace(/\\/g, '/');
    const ext = file.substring(file.lastIndexOf('.')).toLowerCase();
    const isBinary = BINARY_EXTENSIONS.has(ext);

    if (isBinary) {
      const buffer = await bunFile.arrayBuffer();
      files[key] = Buffer.from(buffer).toString('base64');
    } else {
      files[key] = await bunFile.text();
    }
  }

  const fileCount = Object.keys(files).length;
  await Bun.write(OUTPUT_FILE, fullSource(files));
  console.log(`✅ Studio embed generated: ${fileCount} files → ${OUTPUT_FILE}`);
  console.log('   Reminder: do not commit this file — restore the stub before git add.');
}

await generateEmbed();
