export interface ExtensionCatalogEntry {
  name: string;
  displayName: string;
  description: string;
  category: string;
  version: string;
  author: string;
  tags: string[];
  permissions: string[];
  /** Direct download URL for the extension package (.tar.gz). Present when the registry serves packages. */
  download_url?: string;
}

export const EXTENSION_CATALOG: ExtensionCatalogEntry[] = [
  // ── Analytics ─────────────────────────────────────────────────
  // analytics/insights — promoted to engine core, no longer a separate extension
  {
    name: 'analytics/quality',
    displayName: 'Data Quality',
    description: 'Automated data quality scans, anomaly detection and issue management',
    category: 'analytics',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['analytics', 'quality', 'anomalies'],
    permissions: ['database'],
  },

  // ── Auth ──────────────────────────────────────────────────────
  {
    name: 'auth/ldap',
    displayName: 'LDAP / Active Directory',
    description: 'Authenticate users via LDAP or Active Directory',
    category: 'auth',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['auth', 'ldap', 'active-directory', 'sso'],
    permissions: ['database'],
  },
  {
    name: 'auth/saml',
    displayName: 'SAML 2.0 SSO',
    description: 'SAML 2.0 Single Sign-On with external Identity Providers (Okta, Azure AD, Google Workspace)',
    category: 'auth',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['auth', 'saml', 'sso', 'okta', 'azure'],
    permissions: ['database'],
  },

  // ── Communications ────────────────────────────────────────────
  {
    name: 'communications/mail',
    displayName: 'Mail Client',
    description: 'Full IMAP/SMTP email client with AI features, Sieve filtering, and contacts',
    category: 'communications',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['mail', 'email', 'imap', 'smtp'],
    permissions: ['database', 'settings'],
  },
  {
    name: 'sms',
    displayName: 'SMS / Push Notifications',
    description: 'Send SMS via Twilio or Vonage with templates and delivery tracking',
    category: 'communications',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['sms', 'notifications', 'twilio', 'vonage'],
    permissions: ['database'],
  },

  // ── Compliance ────────────────────────────────────────────────
  {
    name: 'compliance/gdpr',
    displayName: 'GDPR Compliance',
    description: 'Data export and right to erasure (GDPR Art. 15, 17)',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['compliance', 'gdpr', 'privacy'],
    permissions: ['database'],
  },
  {
    name: 'compliance/ro/documents',
    displayName: 'Documents RO',
    description: 'Romanian compliance document management — contracts, PVs, NIRs, dispozitii de plata',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['documents', 'contracts', 'romania'],
    permissions: ['database'],
  },
  {
    name: 'compliance/ro/efactura',
    displayName: 'e-Factura RO',
    description: 'Romanian e-Invoice (e-Factura) integration with ANAF — generate, validate, and submit UBL XML invoices',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['invoicing', 'anaf', 'romania', 'ubl'],
    permissions: ['database'],
  },
  {
    name: 'compliance/ro/etransport',
    displayName: 'e-Transport RO',
    description: 'Romanian e-Transport monitoring system — declare and track road transport of goods via ANAF',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['transport', 'anaf', 'romania', 'logistics'],
    permissions: ['database'],
  },
  {
    name: 'compliance/ro/procurement',
    displayName: 'Achizitii Publice RO',
    description: 'Romanian public procurement management — purchase orders, supplier registry, budget tracking',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['procurement', 'suppliers', 'budget', 'romania'],
    permissions: ['database'],
  },
  {
    name: 'compliance/ro/saft',
    displayName: 'SAF-T RO',
    description: 'Romanian Standard Audit File for Tax (SAF-T D.394) — generate XML audit files for ANAF',
    category: 'compliance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['saft', 'tax', 'anaf', 'romania'],
    permissions: ['database'],
  },

  // ── Content ───────────────────────────────────────────────────
  {
    name: 'content/document-templates',
    displayName: 'Document Templates',
    description: 'Admin-managed HTML/PDF templates with variable interpolation and async generation',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['documents', 'templates', 'pdf'],
    permissions: ['database'],
  },
  {
    name: 'content/documents',
    displayName: 'Document Generator',
    description: 'Generate PDF documents from templates with data binding',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['documents', 'pdf', 'templates'],
    permissions: ['database'],
  },
  {
    name: 'content/drafts',
    displayName: 'Content Drafts',
    description: 'Draft/publish workflow for content collections',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['cms', 'drafts', 'publishing'],
    permissions: ['database'],
  },
  {
    name: 'content/media',
    displayName: 'Media Library',
    description: 'Media folders, files, and tags management',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['media', 'files', 'images'],
    permissions: ['database', 'storage'],
  },
  {
    name: 'content/page-builder',
    displayName: 'Page Builder',
    description: 'Visual CMS page builder with drag-and-drop sections, blocks, SEO fields, and live preview',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['cms', 'pages', 'content'],
    permissions: ['database', 'storage'],
  },
  {
    name: 'forms',
    displayName: 'Form Builder',
    description: 'Drag-and-drop form builder with public submission endpoints',
    category: 'content',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['forms', 'submissions', 'builder'],
    permissions: ['database'],
  },

  // ── CRM ───────────────────────────────────────────────────────
  {
    name: 'crm',
    displayName: 'CRM',
    description: 'Contacts, Organizations, and Transactions — core Business OS data layer',
    category: 'business',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['crm', 'contacts', 'sales'],
    permissions: ['database'],
  },

  // ── Data ──────────────────────────────────────────────────────
  {
    name: 'data/export',
    displayName: 'Data Export',
    description: 'Export collection data as JSON, CSV or NDJSON with filtering support',
    category: 'data',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['export', 'csv', 'json', 'data'],
    permissions: ['database'],
  },
  {
    name: 'data/import',
    displayName: 'Data Import',
    description: 'Import collection data from CSV or JSON files with column mapping and background processing',
    category: 'data',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['import', 'csv', 'json', 'data'],
    permissions: ['database'],
  },

  // ── Developer ─────────────────────────────────────────────────
  {
    name: 'developer/api-docs',
    displayName: 'API Documentation',
    description: 'Swagger UI + OpenAPI spec auto-generated from collections',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['api', 'swagger', 'openapi', 'docs'],
    permissions: ['database'],
  },
  {
    name: 'developer/byod',
    displayName: 'BYOD Import',
    description: 'External database schema introspection and import',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['byod', 'introspection', 'migration'],
    permissions: ['database'],
  },
  {
    name: 'developer/database',
    displayName: 'Database Management',
    description: 'PostgreSQL functions, triggers, enums, roles, RLS',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['database', 'postgresql', 'triggers', 'rls'],
    permissions: ['database'],
  },
  {
    name: 'developer/edge-functions',
    displayName: 'Edge Functions',
    description: 'Write and deploy TypeScript serverless functions directly inside the engine with a sandboxed runtime',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['functions', 'serverless', 'typescript'],
    permissions: ['database'],
  },
  {
    name: 'developer/graphql',
    displayName: 'GraphQL API',
    description: 'Auto-generated GraphQL API with playground for all collections',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['graphql', 'api', 'playground'],
    permissions: ['database'],
  },
  // developer/saved-queries — promoted to engine core
  // developer/schema-branches — promoted to engine core
  {
    name: 'developer/validation',
    displayName: 'Data Validation',
    description: 'Field-level validation rules with AI-assisted natural language rule generation',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['validation', 'rules', 'ai'],
    permissions: ['database'],
  },
  {
    name: 'developer/views',
    displayName: 'Alternative Views',
    description: 'Calendar, Card, and List views for collection data — installable alongside the default Table view',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['views', 'calendar', 'kanban', 'list'],
    permissions: [],
  },
  {
    name: 'search',
    displayName: 'Search Adapter',
    description: 'Full-text search via MeiliSearch or Typesense with automatic record sync',
    category: 'developer',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['search', 'fulltext', 'meilisearch', 'typesense'],
    permissions: ['database'],
  },

  // ── Billing ───────────────────────────────────────────────────
  {
    name: 'billing',
    displayName: 'Billing & Usage',
    description: 'Usage metering and Stripe billing integration',
    category: 'billing',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['billing', 'stripe', 'usage', 'metering'],
    permissions: ['database'],
  },

  // ── eCommerce ─────────────────────────────────────────────────
  {
    name: 'ecommerce/store',
    displayName: 'eCommerce',
    description: 'Product catalog, orders, customer management, coupons and public storefront API',
    category: 'ecommerce',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['ecommerce', 'store', 'orders', 'products'],
    permissions: ['database'],
  },

  // ── Finance ───────────────────────────────────────────────────
  {
    name: 'finance/accounting',
    displayName: 'Accounting',
    description: 'Double-entry bookkeeping, chart of accounts, journal entries, P&L and balance sheet reports',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['accounting', 'bookkeeping', 'finance'],
    permissions: ['database'],
  },
  {
    name: 'finance/banking',
    displayName: 'Banking Sync',
    description: 'Import bank statements, auto-reconcile transactions with invoices and track cash flow',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['banking', 'reconciliation', 'cashflow'],
    permissions: ['database'],
  },
  {
    name: 'finance/expenses',
    displayName: 'Expenses',
    description: 'Employee expense reports with receipt management, categorization and approval flow',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['expenses', 'receipts', 'approvals'],
    permissions: ['database'],
  },
  {
    name: 'finance/invoicing',
    displayName: 'Invoicing',
    description: 'Recurring invoices, payment tracking and overdue management',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['invoicing', 'payments', 'billing'],
    permissions: ['database'],
  },
  {
    name: 'finance/quotes',
    displayName: 'Quotes & Proposals',
    description: 'Generate branded PDF quotes and proposals linked to CRM contacts, with convert-to-invoice action',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['quotes', 'proposals', 'pdf', 'crm'],
    permissions: ['database'],
  },
  {
    name: 'finance/subscriptions',
    displayName: 'Subscriptions',
    description: 'Recurring billing plans, subscriber management, MRR/ARR tracking and Stripe integration',
    category: 'finance',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['subscriptions', 'billing', 'stripe', 'mrr'],
    permissions: ['database'],
  },

  // ── Geospatial ────────────────────────────────────────────────
  {
    name: 'geospatial/postgis',
    displayName: 'Geospatial',
    description: 'Location field type, map views in Studio, proximity search, bbox queries, clustering, and geofences',
    category: 'geospatial',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['maps', 'location', 'geospatial', 'postgis'],
    permissions: ['database'],
  },

  // ── HR ────────────────────────────────────────────────────────
  {
    name: 'hr/employees',
    displayName: 'HR',
    description: 'Employee records, departments, job positions, contracts and onboarding checklists',
    category: 'hr',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['hr', 'employees', 'departments'],
    permissions: ['database'],
  },
  {
    name: 'hr/leave',
    displayName: 'Leave Management',
    description: 'Vacation and leave requests with balance tracking, approval workflow and calendar view',
    category: 'hr',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['hr', 'leave', 'vacation', 'approvals'],
    permissions: ['database'],
  },
  {
    name: 'hr/payroll',
    displayName: 'Payroll RO',
    description: 'Romanian payroll: CAS, CASS, income tax calculations, meal vouchers and Revisal XML export',
    category: 'hr',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['payroll', 'hr', 'romania', 'revisal'],
    permissions: ['database'],
  },
  {
    name: 'hr/time-tracking',
    displayName: 'Time Tracking',
    description: 'Timesheets, project-based time logging, billable hours and client reports',
    category: 'hr',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['timesheets', 'billing', 'projects', 'hr'],
    permissions: ['database'],
  },

  // ── i18n ──────────────────────────────────────────────────────
  {
    name: 'i18n/translations',
    displayName: 'Translations',
    description: 'Internationalization: manage locales, translation keys and per-locale string values',
    category: 'i18n',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['i18n', 'translations', 'locales'],
    permissions: ['database'],
  },

  // ── Integrations ──────────────────────────────────────────────
  {
    name: 'integrations/api-connector',
    displayName: 'API Connector',
    description: 'No-code HTTP integrations — connect external REST APIs with field mapping, retry logic and execution logs',
    category: 'integrations',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['integrations', 'api', 'http', 'webhooks'],
    permissions: ['database'],
  },

  // ── Operations ────────────────────────────────────────────────
  {
    name: 'operations/assets',
    displayName: 'Fixed Assets',
    description: 'Fixed asset register, straight-line and declining balance depreciation, maintenance schedules',
    category: 'operations',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['assets', 'depreciation', 'maintenance'],
    permissions: ['database'],
  },
  // operations/backup — promoted to engine core
  {
    name: 'operations/inventory',
    displayName: 'Inventory',
    description: 'Warehouses, SKUs, stock movements, reorder alerts and barcode support',
    category: 'operations',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['inventory', 'warehouse', 'stock', 'barcode'],
    permissions: ['database'],
  },
  {
    name: 'operations/pos',
    displayName: 'Point of Sale',
    description: 'Cash register, receipt generation, end-of-day reports and inventory integration',
    category: 'operations',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['pos', 'retail', 'receipts', 'inventory'],
    permissions: ['database'],
  },

  // ── Projects ──────────────────────────────────────────────────
  {
    name: 'projects/helpdesk',
    displayName: 'Helpdesk',
    description: 'Support ticket management with SLA timers, priorities, assignments and message threads',
    category: 'projects',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['helpdesk', 'tickets', 'support', 'sla'],
    permissions: ['database'],
  },
  {
    name: 'projects/management',
    displayName: 'Project Management',
    description: 'Projects, milestones, tasks, kanban board, team assignments and progress tracking',
    category: 'projects',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['projects', 'tasks', 'kanban', 'milestones'],
    permissions: ['database'],
  },

  // ── Storage ───────────────────────────────────────────────────
  {
    name: 'storage/cloud',
    displayName: 'Cloud Storage',
    description: 'File versioning, trash bin, public share links, and storage quotas',
    category: 'storage',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['storage', 'files', 'cloud', 'sharing'],
    permissions: ['database', 'storage'],
  },

  // ── Workflow ──────────────────────────────────────────────────
  {
    name: 'workflow/approvals',
    displayName: 'Approval Workflows',
    description: 'Multi-step approval workflows with email notifications, SLA tracking, and full audit trail',
    category: 'workflow',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['workflow', 'approvals', 'notifications'],
    permissions: ['database', 'email'],
  },
  {
    name: 'workflow/checklists',
    displayName: 'Checklists',
    description: 'Dynamic checklists and forms with scoring, conditional logic, and response analytics',
    category: 'workflow',
    version: '1.0.0',
    author: 'Zveltio',
    tags: ['forms', 'checklists', 'scoring'],
    permissions: ['database'],
  },
];
