#!/usr/bin/env bun
/**
 * audit-inventory.ts — Cross-reference state-changing route handlers with
 * audit-log call sites. Produces:
 *
 *   docs/AUDIT-COVERAGE.md   (human-readable matrix + gap list)
 *   audit-inventory.json     (CI-consumable, for regression checks)
 *
 * Rules:
 *   - A "mutating route" is any POST/PATCH/PUT/DELETE handler in
 *     packages/engine/src/routes/**.ts.
 *   - A route is considered "audited" if `auditLog(` appears between the
 *     handler's opening brace and the next sibling handler (or EOF).
 *   - The inventory is intentionally lexical, not type-aware: we want to
 *     flag handlers that don't have a visible auditLog call, even if some
 *     internal helper does the writing. Better one false positive than one
 *     missing audit entry.
 *
 * Run via: `bun run scripts/audit-inventory.ts`
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

const ROUTES_DIR = 'packages/engine/src/routes';
const OUTPUT_MD = 'docs/AUDIT-COVERAGE.md';
const OUTPUT_JSON = 'audit-inventory.json';

interface RouteHandler {
  file: string;
  method: string;
  path: string;
  lineStart: number;
  lineEnd: number;
  audited: boolean;
  /** Exempt categories like read-only endpoints accidentally matched. */
  reason?: string;
}

const HANDLER_RE = /\b(?:app|router)\.(post|patch|put|delete)\(\s*(['"`])([^'"`]+)\2/g;

async function listRouteFiles(): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(ROUTES_DIR, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts')) {
      files.push(join(ROUTES_DIR, entry.name));
    }
  }
  return files.sort();
}

async function scanFile(file: string): Promise<RouteHandler[]> {
  const src = await readFile(file, 'utf8');
  const lines = src.split('\n');
  const handlers: RouteHandler[] = [];

  // First, find all handler start offsets along with line numbers.
  type Match = { method: string; path: string; offset: number; line: number };
  const matches: Match[] = [];
  let m: RegExpExecArray | null;
  HANDLER_RE.lastIndex = 0;
  while ((m = HANDLER_RE.exec(src)) !== null) {
    const offset = m.index;
    const line = src.slice(0, offset).split('\n').length;
    matches.push({ method: m[1].toUpperCase(), path: m[3], offset, line });
  }

  for (let i = 0; i < matches.length; i++) {
    const cur = matches[i];
    const next = matches[i + 1];
    const sliceStart = cur.offset;
    const sliceEnd = next ? next.offset : src.length;
    const block = src.slice(sliceStart, sliceEnd);
    const audited = /\bauditLog\s*\(/.test(block);
    const endLine = next ? next.line - 1 : lines.length;
    handlers.push({
      file,
      method: cur.method,
      path: cur.path,
      lineStart: cur.line,
      lineEnd: endLine,
      audited,
    });
  }

  return handlers;
}

async function main() {
  const files = await listRouteFiles();
  const all: RouteHandler[] = [];
  for (const f of files) {
    all.push(...(await scanFile(f)));
  }

  const covered = all.filter((h) => h.audited);
  const gaps = all.filter((h) => !h.audited);

  // Group gaps by file for readability.
  const gapsByFile = new Map<string, RouteHandler[]>();
  for (const g of gaps) {
    const fname = g.file.split(/[\\/]/).pop()!;
    if (!gapsByFile.has(fname)) gapsByFile.set(fname, []);
    gapsByFile.get(fname)!.push(g);
  }

  const totalPct = all.length === 0 ? 0 : Math.round((covered.length / all.length) * 100);

  // ── Markdown report ──────────────────────────────────────────────
  const md: string[] = [];
  md.push('# Audit Coverage Inventory');
  md.push('');
  md.push('> Auto-generated by `scripts/audit-inventory.ts`. Do not edit by hand —');
  md.push('> re-run the script after adding/removing routes.');
  md.push('');
  md.push(`Generated: ${new Date().toISOString()}`);
  md.push('');
  md.push('## Summary');
  md.push('');
  md.push(`- Mutating route handlers: **${all.length}**`);
  md.push(`- With visible \`auditLog()\` call: **${covered.length}** (${totalPct}%)`);
  md.push(`- Without audit call: **${gaps.length}**`);
  md.push('');
  md.push('## Coverage policy');
  md.push('');
  md.push('Every mutating route SHOULD call `auditLog()` for these classes of event:');
  md.push('');
  md.push('1. **Authentication & authorization**: login (success/fail), logout, permission changes, role changes, API-key lifecycle.');
  md.push('2. **Schema changes**: collection/field create / drop / rename, RLS rule edits, settings.');
  md.push('3. **Privileged execution**: SQL editor, god-mode, extension load/unload, backup create/restore, PITR.');
  md.push('4. **Data exfiltration paths**: bulk export, backup download, large CSV imports.');
  md.push('');
  md.push('Per-record CRUD (`POST /api/data/:collection`) is NOT in scope — `zv_revisions`');
  md.push('captures the data-level change history. The audit log is for *operational* events.');
  md.push('Handlers in the gap list below are flagged so a human can decide which category they fall into.');
  md.push('');
  md.push('## Gaps (handlers without visible `auditLog`)');
  md.push('');

  if (gaps.length === 0) {
    md.push('_None — full coverage._');
  } else {
    for (const [fname, list] of [...gapsByFile.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      md.push(`### \`${fname}\``);
      md.push('');
      md.push('| Method | Path | Line |');
      md.push('| ------ | ---- | ---- |');
      for (const h of list) {
        md.push(`| ${h.method} | \`${h.path}\` | ${h.lineStart} |`);
      }
      md.push('');
    }
  }

  md.push('## Covered (for reference)');
  md.push('');
  if (covered.length === 0) {
    md.push('_None._');
  } else {
    md.push('| File | Method | Path | Line |');
    md.push('| ---- | ------ | ---- | ---- |');
    for (const h of covered) {
      const fname = h.file.split(/[\\/]/).pop();
      md.push(`| \`${fname}\` | ${h.method} | \`${h.path}\` | ${h.lineStart} |`);
    }
  }

  await mkdir('docs', { recursive: true });
  await writeFile(OUTPUT_MD, md.join('\n') + '\n');
  await writeFile(OUTPUT_JSON, JSON.stringify({
    generatedAt: new Date().toISOString(),
    totals: { all: all.length, covered: covered.length, gaps: gaps.length, percent: totalPct },
    gaps,
    covered,
  }, null, 2));

  console.log(`✓ ${all.length} mutating handlers — ${covered.length} audited (${totalPct}%), ${gaps.length} gaps`);
  console.log(`  → ${OUTPUT_MD}`);
  console.log(`  → ${OUTPUT_JSON}`);
}

main().catch((err) => {
  console.error('audit-inventory failed:', err);
  process.exit(1);
});
